<?php
 /*Defining of file name in variable*/
ob_start();
define('FILENAME_HEADER_MAIN','header.php');
define('FILENAME_FOOTER_MAIN','footer.php');
define('FILENAME_PUBLIC_BANNER','banner.php');
define('FILENAME_PUBLIC__MAIN','main.php');
define('FILENAME_PUBLIC_TEST_DETAILS','test_details.php');
define('FILENAME_TEST_ATTEMPT','test_attempt.php');
define('FILENAME_TEST_USER_DETAIL','user_details.php');
define('FILENAME_TEST_CLASS','public_test_class.php');
define('FILENAME_TEST_PASS','test_pass.php');
define('FILENAME_TEST_REP_CONF','test_attempt_alert.php');
define('FILENAME_TEST_REPORT','viewtest_report.php');
define('FILENAME_TEST_CERTIFICATE','test_certifications.php');
define('FILENAME_TEST_UDETAIS_MORE','user_details_more.php');
define('FILENAME_TEST_SIGN_IN','user_login.php');
define('FILENAME_TEST_MY_ACCOUNT','my_account.php');
define('FILENAME_TEST_EMAIL_EXIST','user_exist.php');
#############Admin Section Start #################
define('FILENAME_TEST_QUESTION_LIST','qstn_list.php');
define('FILENAME_TEST_ADD_QSTN','add_qstn.php');
define('FILENAME_TEST_EDIT_QSTN','edit_qstn.php');
define('FILENAME_TEST_LIST','test_list.php');
define('FILENAME_ADD_TEST','add_test.php');
define('FILENAME_ADD_TEST_QSTN','add_test_qstn.php');
define('FILENAME_LEFT_NAV','left_nav.php');
define('FILENAME_QUESTION_DETAILS','qstn_details.php');
define('FILENAME_TEST_QUESTION_PREVIEW','question_preview.php');
define('FILENAME_TEST_PREVIEW','test_preview.php');
define('FILENAME_EDIT_TEST','edit_test.php');
define('FILENAME_TEST_PUBLISH','test_publish.php');
define('FILENAME_TEST_INFO','test_info.php');
define('FILENAME_TEST_USER_LIST','user_list.php');
define('FILENAME_TEST_CHANEG_PASS','change_pass.php');
define('FILENAME_TEST_OTHERS','other_test.php');
define('FILENAME_USER_TEST','user_test_dtl.php');
define('FILENAME_USER_DASHBOARD','dashboard.php');
define('FILENAME_IS_CATEGORYIZE','categorize_dtl.php');
define('FILENAME_ADMIN_REPORT','admin_test_report.php');
define('FILENAME_TEST_QST_CAT','test_attempt_categ.php');

?>  
